name = "Honkai: Star Rail"
author = "Darkkal44"
background = "video"
background_file = "bg.mp4"

[[font]]
file = "font.ttf"
family = "DIN Next"
license = "Commercial (Monotype)"
url = ""

[supports]
clock_format = true
date_format = true
background = true
colors = true
fonts = ["text", "clock"]
motion = true
