name = "Girl · Coffee"
author = "Darkkal44"
background = "image"
background_file = "bg.png"

[supports]
screensaver = true
clock_format = true
date_format = true
background = true
colors = true
fonts = ["text", "clock"]
motion = true
variants = ["light", "dark"]
default_variant = "light"
