name = "Tape"
family = "Clockwork"
author = "Darkkal44"
background = "color"

[supports]
clock_format = true
date_format = true
background = true
colors = true
fonts = ["text", "clock"]
motion = true
variants = ["dark", "light"]
default_variant = "dark"
