name = "Nothing"
author = "Darkkal44"
background = "color"

[[font]]
file = "NDot55.otf"
family = "NDot 55"
license = "Nothing brand use only"
url = ""

[supports]
screensaver = true
clock_format = true
date_format = true
background = true
colors = true
fonts = ["text", "clock"]
motion = true
variants = ["light", "dark"]
default_variant = "light"
