name = "Sakura"
family = "Pixel"
author = "Darkkal44"
background = "video"
background_file = "bg.mp4"

[supports]
screensaver = true
clock_format = true
date_format = true
background = true
colors = true
fonts = ["text", "clock"]
motion = true

[[color]]
key = "colorSlate"
label = "Secondary text"
material = "on_surface_variant"
