name = "Sword"
author = "Darkkal44"
background = "video"
background_file = "bg.mp4"

[[font]]
file = "The Last Shuriken.ttf"
family = "The Last Shuriken"
license = "Free for personal use (Arterfak Project)"
url = "https://www.dafont.com/the-last-shuriken.font"

[supports]
screensaver = true
clock_format = true
date_format = true
background = true
colors = true
fonts = ["text", "clock"]
motion = true
