name = "NieR: Automata"
author = "Darkkal44"
background = "image"

[[font]]
file = "FOT-Rodin Pro DB.otf"
family = "FOT-Rodin Pro DB"
license = "Commercial (Fontworks)"
url = "https://fonts.adobe.com/fonts/fot-rodin-pron"

[supports]
screensaver = true
clock_format = true
date_format = true
colors = true
fonts = ["text", "clock"]
motion = true
variants = ["light", "dark"]
default_variant = "light"
